version: 2
updates:
  # API application
  - package-ecosystem: "npm"
    directory: "/src/api"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  # Rembg application
  - package-ecosystem: "pip"
    directory: "/src/rembg"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  # Combiner application
  - package-ecosystem: "npm"
    directory: "/src/combiner"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot :robot:"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
